# Generated by Django 5.0.6 on 2024-07-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='owner_img')),
                ('resume', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('kaggle_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('other_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('hobby', 'Hobby'), ('professional', 'Professional'), ('academic', 'Academic')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='skills.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('out_of', models.PositiveIntegerField()),
                ('given_by', models.CharField(max_length=100)),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('paper', models.FileField(upload_to='certificates')),
                ('image', models.ImageField(upload_to='certificate_img')),
                ('url', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='skills.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=400)),
                ('project_links', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='skills.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=30)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('edu_languages', models.CharField(max_length=100)),
                ('main_courses', models.TextField(max_length=300)),
                ('focus', models.CharField(max_length=400)),
                ('diploma', models.FileField(upload_to='diplomas')),
                ('diploma_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='diploma_img')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='skills.owner')),
                ('projects', models.ManyToManyField(blank=True, to='skills.project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.certificate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.owner')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='skills.skill'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('used_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='skills.owner')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(to='skills.tool'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('company_links', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='skills.owner')),
                ('skills', models.ManyToManyField(to='skills.skill')),
                ('tools', models.ManyToManyField(to='skills.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_work', to='skills.owner')),
                ('skills', models.ManyToManyField(to='skills.skill')),
                ('tools', models.ManyToManyField(to='skills.tool')),
            ],
        ),
    ]
