# Generated by Django 5.0.6 on 2024-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='Re', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('associate', 'Associate'), ('master', 'Master'), ('phd', 'PhD')], max_length=30),
        ),
    ]
