# Generated by Django 5.0.6 on 2024-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_education_major_alter_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
