# Generated by Django 5.0.6 on 2024-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_certificate_out_of_alter_certificate_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_img'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
