# Generated by Django 5.0.6 on 2024-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='awards'),
        ),
        migrations.AddField(
            model_name='awards',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
