# Generated by Django 5.0.6 on 2024-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_awards_img_awards_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='Key Achievents', max_length=300),
        ),
    ]
