# Generated by Django 5.0.6 on 2024-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='favorite_tools',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='owner',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='owner',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
