# Generated by Django 5.0.6 on 2024-07-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_owner_favorite_tools_owner_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cando', to='skills.owner')),
                ('tool_to_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.tool')),
            ],
        ),
    ]
