# Generated by Django 5.0.6 on 2024-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_languages_owner_email_owner_phone_owner_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='location',
            field=models.CharField(default='Uzbekistan', max_length=100),
        ),
    ]
