# Generated by Django 5.0.6 on 2024-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_owner_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='cando',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='education',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='languages',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon'),
        ),
    ]
