# Generated by Django 5.0.6 on 2024-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_awards_icon_cando_icon_certificate_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
